# Generated by Django 4.1.4 on 2022-12-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_city_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='user',
        ),
    ]
